version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: churchapp-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: church_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
